### ISSUE TITLE
Add support for REGEX without flags

### ISSUE THREAD

**Issue by patofp** [gsk-aiops/bellman#128]

**Comment by JNKHunter** [comment]
Hey @patofp, would REGEX allow us to run the following query? Is there any other part of this query that is not supported? I can't tell which part of the query isn't supported because the error message is a little bit cryptic:

```
java.util.NoSuchElementException: Either.right.value on Left
  at scala.util.Either$RightProjection.get(Either.scala:453)
  at com.gsk.kg.engine.syntax.package$SparQLSyntaxOnDataFrame.sparql(package.scala:20)
  at com.gsk.kg.engine.syntax.package$SparQLSyntaxOnDataFrame.sparql(package.scala:27)
  ... 56 elided
```

```
SELECT ?s ?o WHERE {
        ?s a <http://gsk-kg.rdip.gsk.com/dm/1.0/UMLSConcept> .
        ?s <http://gsk-kg.rdip.gsk.com/dm/1.0/conceptLink> ?o .
        FILTER (regex(str(?o),"https://meshb.nlm.nih.gov/record/ui")
            || regex(str(?o),"https://www.ncbi.nlm.nih.gov/taxonomy/")
            || regex(str(?o),"https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=")
        ) .
    }
```

**Comment by patofp** [comment]
Yeah, we don’t have support for regex right now. I don’t see any other reason why it would throw that error. Let me me do some more investigation on monday so I can confirm. 😉
