### ISSUE TITLE
Illegal N-Triples syntax; works fine in Sansa

### ISSUE THREAD

**Issue by bkosuru** [gsk-aiops/bellman#140]
```
Caused by: java.lang.Exception: WARN: Illegal N-Triples syntax. Ignoring triple <http://gsk-kg.rdip.gsk.com/nlp/textelem#2020-06-17T17:23:21.382Zd989b795-96ca-4aa7-8c05-8b956a19bb3f.body.2.0.text3> <http://gsk-kg.rdip.gsk.com/dm/1.0/text> "As shown in Table 3, 120 (24%) patients in the DS clinic had a documented history of thyroid-related diagnosis: 2% congenital hypothyroidism, 10% subclinical hypothyroidism, 1% overt hypothyroidism, 4.5% with isolated hyperthyrotropinemia, 4.3% unknown hypothyroidism, and 1.6% hyperthyroidism. There was no difference in rates of any type of thyroid disease between males and females; mean serum TSH and FT4 at diagnosis are shown in Table 3. There was a statistically significant difference in TSH and mean FT4 between those with overt and subclinical hypothyroidism (p &lt; 0.005). All those with hyperthyroidism were diagnosed with Graves disease and treated with methimazole with good response to therapy.  "^^<xsd:string> .
  at net.sansa_stack.rdf.spark.io.ntriples.NTriplesRelation.net$sansa_stack$rdf$spark$io$ntriples$NTriplesRelation$$parseRegexPattern(NTriplesRelation.scala:191)
  at net.sansa_stack.rdf.spark.io.ntriples.NTriplesRelation$$anonfun$6.apply(NTriplesRelation.scala:88)
  at net.sansa_stack.rdf.spark.io.ntriples.NTriplesRelation$$anonfun$6.apply(NTriplesRelation.scala:87)
  at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
  at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
  at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage9.processNext(Unknown Source)
  at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
  at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$11$$anon$1.hasNext(WholeStageCodegenExec.scala:624)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
  at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:148)
  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
  at org.apache.spark.scheduler.Task.run(Task.scala:121)
  at org.apache.spark.executor.Executor$TaskRunner$$anonfun$11.apply(Executor.scala:407)
  at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1408)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:413)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
```

**Comment by JNKHunter** [comment]
Hi @bkosuru . Can you please provide a bit more context? What was the query?

**Comment by bkosuru** [comment]
Here is the query. I will send the sample data.
df4.sparql("""

PREFIX dm: <http://gsk-kg.rdip.gsk.com/dm/1.0/>
SELECT ?objde ?objStartIdx ?objEndIdx ?objText ?objle
WHERE
{
?objde dm:indexStart ?objStartIdx .
?objde dm:indexEnd ?objEndIdx .
?objde dm:text ?objText .
?objde dm:entityLink ?objle .
}

LIMIT 10

""").show(10,false)

**Comment by patofp** [comment]
[AIPL-3416](https://myjira.gsk.com/browse/AIPL-3416)
