### ISSUE TITLE
QueryParseException with BIND

### ISSUE THREAD

**Issue by bkosuru** [gsk-aiops/bellman#187]
PREFIX  schema: <http://schema.org/>
PREFIX  rdf:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  xml:  <http://www.w3.org/XML/1998/namespace>
PREFIX  dm:   <http://c.b.com/dm/1.0/>
PREFIX  prism: <http://prismstandard.org/namespaces/basic/2.0/>
PREFIX  litg:  <http://lit-search-api/graph/>
PREFIX  litn:  <http://lit-search-api/node/>
PREFIX  lite:  <http://lit-search-api/edge/>
PREFIX  litp:  <http://lit-search-api/property/>

CONSTRUCT {
  ?Document a litn:Document .
  ?Document litp:docID ?docid .
}
WHERE{
  ?d a dm:Document .
  BIND(STRAFTER(str(?d), #) as ?docid) .
  BIND(URI(CONCAT(http://lit-search-api/node/doc#, ?docid)) as ?Document) .
}

Exception in thread "main" org.apache.jena.query.QueryParseException: Encountered " "bind" "BIND "" at line 18, column 3.
Was expecting one of:
    <IRIref> ...
    <PNAME_NS> ...
    <PNAME_LN> ...
    <VAR1> ...
    <VAR2> ...
    "exists" ...
    "not" ...
    "agg" ...
    "count" ...
    "min" ...
    "max" ...
    "sum" ...
    "avg" ...
    "median" ...
    "mode" ...
    "stdev" ...
    "stdev_samp" ...
    "stdev_pop" ...
    "variance" ...
    "var_samp" ...
    "var_pop" ...
    "sample" ...
    "group_concat" ...
    "bound" ...
    "coalesce" ...
    "if" ...
    "bnode" ...
    "iri" ...
    "uri" ...
    "call" ...
    "str" ...
    "strlang" ...
    "strdt" ...
    "datatype" ...
    "lang" ...
    "langmatches" ...
    "isURI" ...
    "isIRI" ...
    "isBlank" ...
    "isLiteral" ...
    "isNumeric" ...
    "regex" ...
    "sameTerm" ...
    "RAND" ...
    "ABS" ...
    "CEIL" ...
    "FLOOR" ...
    "ROUND" ...
    "CONCAT" ...
    "SUBSTR" ...
    "STRLEN" ...
    "REPLACE" ...
    "UCASE" ...
    "LCASE" ...
    "ENCODE_FOR_URI" ...
    "CONTAINS" ...
    "STRSTARTS" ...
    "STRENDS" ...
    "STRBEFORE" ...
    "STRAFTER" ...
    "YEAR" ...
    "MONTH" ...
    "DAY" ...
    "HOURS" ...
    "MINUTES" ...
    "SECONDS" ...
    "TIMEZONE" ...
    "TZ" ...
    "NOW" ...
    "UUID" ...
    "STRUUID" ...
    "VERSION" ...
    "MD5" ...
    "SHA1" ...
    "SHA256" ...
    "SHA384" ...
    "SHA512" ...
    "true" ...
    "false" ...
    <INTEGER> ...
    <DECIMAL> ...
    <DOUBLE> ...
    <INTEGER_POSITIVE> ...
    <DECIMAL_POSITIVE> ...
    <DOUBLE_POSITIVE> ...
    <INTEGER_NEGATIVE> ...
    <DECIMAL_NEGATIVE> ...
    <DOUBLE_NEGATIVE> ...
    <STRING_LITERAL1> ...
    <STRING_LITERAL2> ...
    <STRING_LITERAL_LONG1> ...
    <STRING_LITERAL_LONG2> ...
    "(" ...
    "!" ...
    "+" ...
    "-" ...
    
	at org.apache.jena.sparql.lang.ParserARQ.perform(ParserARQ.java:100)
	at org.apache.jena.sparql.lang.ParserARQ.parse$(ParserARQ.java:52)
	at org.apache.jena.sparql.lang.SPARQLParser.parse(SPARQLParser.java:34)
	at org.apache.jena.query.QueryFactory.parse(QueryFactory.java:151)
	at org.apache.jena.query.QueryFactory.create(QueryFactory.java:83)
	at org.apache.jena.query.QueryFactory.create(QueryFactory.java:56)
	at org.apache.jena.query.QueryFactory.create(QueryFactory.java:44)

**Comment by bkosuru** [comment]
I was missing quotes around url. Not a bug
